site_name: Data Warehouse Documentation

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide: user-guide.md
  - API Documentation: api/index.md

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
